apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
  namespace: change_me-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi
